/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ArenaOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getMatchRecord"
      | "isMatchRecorded"
      | "matchRecords"
      | "owner"
      | "recordMatchResult"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MatchRecorded" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getMatchRecord",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isMatchRecorded",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "matchRecords",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordMatchResult",
    values: [string, AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMatchRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMatchRecorded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordMatchResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MatchRecordedEvent {
  export type InputTuple = [
    matchId: string,
    winner: AddressLike,
    loser: AddressLike,
    combatLogHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    matchId: string,
    winner: string,
    loser: string,
    combatLogHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    matchId: string;
    winner: string;
    loser: string;
    combatLogHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArenaOracle extends BaseContract {
  connect(runner?: ContractRunner | null): ArenaOracle;
  waitForDeployment(): Promise<this>;

  interface: ArenaOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMatchRecord: TypedContractMethod<
    [matchId: string],
    [
      [string, string, string, bigint] & {
        winner: string;
        loser: string;
        combatLogHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  isMatchRecorded: TypedContractMethod<[arg0: string], [boolean], "view">;

  matchRecords: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint] & {
        winner: string;
        loser: string;
        combatLogHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordMatchResult: TypedContractMethod<
    [
      matchId: string,
      winner: AddressLike,
      loser: AddressLike,
      combatLogHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMatchRecord"
  ): TypedContractMethod<
    [matchId: string],
    [
      [string, string, string, bigint] & {
        winner: string;
        loser: string;
        combatLogHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMatchRecorded"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "matchRecords"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint] & {
        winner: string;
        loser: string;
        combatLogHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordMatchResult"
  ): TypedContractMethod<
    [
      matchId: string,
      winner: AddressLike,
      loser: AddressLike,
      combatLogHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MatchRecorded"
  ): TypedContractEvent<
    MatchRecordedEvent.InputTuple,
    MatchRecordedEvent.OutputTuple,
    MatchRecordedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "MatchRecorded(string,address,address,bytes32,uint256)": TypedContractEvent<
      MatchRecordedEvent.InputTuple,
      MatchRecordedEvent.OutputTuple,
      MatchRecordedEvent.OutputObject
    >;
    MatchRecorded: TypedContractEvent<
      MatchRecordedEvent.InputTuple,
      MatchRecordedEvent.OutputTuple,
      MatchRecordedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
